services:
  wordpress:
    build: .
    container_name: momentum_wp
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: momentum
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
    networks:
      - wordpress_network

  db:
    image: mysql:8.0
    container_name: momentum_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: momentum
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: momentum_phpmyadmin
    restart: always
    ports:
      - 8005:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    depends_on:
      - db
    networks:
      - wordpress_network

volumes:
  db_data:

networks:
  wordpress_network:
    driver: bridge
